# Generated by Django 4.0.2 on 2022-02-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
    ]
