# Generated by Django 4.0.2 on 2022-02-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_api', '0003_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
